blank_issues_enabled: true
contact_links:
  - name: "Community Support (Discord)"
    url: https://discord.com/KTbpAEhWsf
    about: "Join our Discord server to get help from the community with common errors and modding."
