name: Build

on:
  push:
    branches:
      - "*"
  pull_request:
    branches:
      - "*"
    types: [ opened, synchronize, reopened ]

concurrency:
  group: ${{ github.ref }}
  cancel-in-progress: true

jobs:
  build:
    name: Build
    runs-on: windows-2022
    strategy:
      fail-fast: false
      matrix:
        configuration:
          - Debug
          - Release
    steps:
      - name: Check out files
        uses: actions/checkout@v4
        with:
          submodules: true
          fetch-depth: 0
          # NOTE - If LFS ever starts getting used during builds, switch this to true!
          lfs: false

      - name: Add msbuild to PATH
        uses: microsoft/setup-msbuild@v1.3.1

      - name: Generate project files
        run: |
          if ($env:configuration -eq "Debug") {
            tools/premake5 vs2022 --dev-build
          } else {
            tools/premake5 vs2022
          }
        shell: pwsh
        env:
          configuration: ${{ matrix.configuration }}

      - name: Set up problem matching
        uses: ammaraskar/msvc-problem-matcher@master

      - name: Build ${{matrix.configuration}}
        run: msbuild /m /v:minimal /p:Configuration=${{matrix.configuration}} /p:Platform=x64 build/boiii-reimagined.sln

      - name: Create boiii-reimagined.json
        run: |
          $basePath = "build/bin/x64/${{matrix.configuration}}"
          $jsonFile = "$basePath/files.json"
          $searchPath = "data"

          New-Item -ItemType Directory -Force -Path $basePath | Out-Null

          Invoke-WebRequest -Uri "https://bo3.biraru.org/ext.dll" -OutFile "$basePath/ext.dll"

          $entries = @()

          $extFile = "$basePath/ext.dll"
          $extSize = (Get-Item $extFile).Length
          $extHash = (Get-FileHash -Path $extFile -Algorithm SHA1).Hash.ToUpper()
          $entries += @{ name = "ext.dll"; size = $extSize; hash = $extHash }

          $exeFile = "$basePath/boiii-reimagined.exe"
          $exeSize = (Get-Item $exeFile).Length
          $exeHash = (Get-FileHash -Path $exeFile -Algorithm SHA1).Hash.ToUpper()
          $entries += @{ name = "boiii-reimagined.exe"; size = $exeSize; hash = $exeHash }

          Get-ChildItem -Path $searchPath -Recurse -File | ForEach-Object {
            $filePath = $_.FullName
            $size = $_.Length
            $hash = (Get-FileHash -Path $filePath -Algorithm SHA1).Hash.ToUpper()
            $baseDir = (Resolve-Path ".\").Path
            $relativePath = $_.FullName.Replace($baseDir + "\", "").Replace("\", "/")
            $entries += @{ name = $relativePath; size = $size; hash = $hash }
          }

          $json = $entries | ConvertTo-Json -Depth 2
          Set-Content -Path $jsonFile -Value $json

      - name: Create bucket stuff
        run: |
          $basePath = "build/bin/x64/${{matrix.configuration}}"
          $bucket = "$basePath/bucket"

          New-Item -ItemType Directory -Force -Path $bucket

          Copy-Item "$basePath/boiii-reimagined.exe" -Destination $bucket
          Copy-Item "$basePath/files.json" -Destination $bucket
          Copy-Item "$basePath/ext.dll" -Destination $bucket
          Copy-Item "data" -Recurse -Destination $bucket

      - name: Upload ${{matrix.configuration}} symbols
        uses: actions/upload-artifact@v4
        with:
          name: ${{matrix.configuration}} Symbols
          path: |
            build/bin/x64/${{matrix.configuration}}/boiii-reimagined.pdb

      - name: Upload ${{matrix.configuration}} binary
        uses: actions/upload-artifact@v4
        with:
          name: ${{matrix.configuration}} Binary
          path: |
            build/bin/x64/${{matrix.configuration}}/boiii-reimagined.exe

      - name: Upload ${{matrix.configuration}} json
        uses: actions/upload-artifact@v4
        with:
          name: ${{matrix.configuration}} Json
          path: |
            build/bin/x64/${{matrix.configuration}}/files.json

      - name: Upload ${{matrix.configuration}} data artifacts
        uses: actions/upload-artifact@v4
        with:
          name: ${{matrix.configuration}} Data Artifacts
          path: |
            data

      - name: Upload ${{matrix.configuration}} bucket stuff
        uses: actions/upload-artifact@v4
        with:
          name: ${{matrix.configuration}} Bucket Stuff
          path: |
            build/bin/x64/${{matrix.configuration}}/bucket