name: Build

on:
  push:
    branches:
      - "*"
  pull_request:
    branches:
      - "*"
    types: [opened, synchronize, reopened]
  workflow_dispatch:

concurrency:
  group: ${{ github.ref }}
  cancel-in-progress: true

jobs:
  build:
    name: Build
    runs-on: windows-2022
    strategy:
      fail-fast: false
      matrix:
        configuration:
          - Debug
          - Release
    steps:
      - name: Check out files
        uses: actions/checkout@v3.5.2
        with:
          submodules: true
          fetch-depth: 0
          # NOTE - If LFS ever starts getting used during builds, switch this to true!
          lfs: false

      - name: Add msbuild to PATH
        uses: microsoft/setup-msbuild@v1.3.1

      - name: Generate project files
        run: tools/premake5 vs2022 --no-check

      - name: Set up problem matching
        uses: ammaraskar/msvc-problem-matcher@master

      - name: Build ${{matrix.configuration}}
        run: msbuild /m /v:minimal /p:Configuration=${{matrix.configuration}} /p:Platform=x64 build/boiii.sln

      - name: Upload ${{matrix.configuration}} symbols
        if: matrix.configuration == 'Release' && github.event_name == 'push' && (github.ref == 'refs/heads/main' || github.ref == 'refs/heads/develop')
        uses: actions/upload-artifact@v3.1.2
        with:
          name: ${{matrix.configuration}} Symbols
          path: |
            build/bin/x64/${{matrix.configuration}}/boiii.pdb

      - name: Upload ${{matrix.configuration}} binary
        if: matrix.configuration == 'Release' && github.event_name == 'push' && (github.ref == 'refs/heads/main' || github.ref == 'refs/heads/develop')
        uses: actions/upload-artifact@v3.1.2
        with:
          name: ${{matrix.configuration}} Binary
          path: |
            build/bin/x64/${{matrix.configuration}}/boiii.exe

      - name: Upload ${{matrix.configuration}} data artifacts
        if: matrix.configuration == 'Release' && github.event_name == 'push' && (github.ref == 'refs/heads/main' || github.ref == 'refs/heads/develop')
        uses: actions/upload-artifact@v3.1.2
        with:
          name: ${{matrix.configuration}} data artifacts
          path: |
            data/*

      - name: LS
        run: Get-ChildItem -Force

  deploy:
    name: Deploy artifacts
    needs: build
    runs-on: ubuntu-latest
    if: github.repository_owner == 'BiraruYT' && github.event_name == 'push' && (github.ref == 'refs/heads/main' || github.ref == 'refs/heads/develop')
    steps:
      - name: Setup environment
        run: echo "BOIII_MASTER_PATH=${{ secrets.BOIII_MASTER_SSH_PATH }}" >> $GITHUB_ENV

      #- name: Setup main environment
      # if: github.ref == 'refs/heads/main'
      #  run: echo "BOIII_MASTER_PATH=${{ secrets.BOIII_MASTER_SSH_PATH }}" >> $GITHUB_ENV

      #- name: Setup develop environment
      #  if: github.ref == 'refs/heads/develop'
      #  run: echo "BOIII_MASTER_PATH=${{ secrets.BOIII_MASTER_SSH_PATH_DEV }}" >> $GITHUB_ENV

      - name: Download Release binaries
        uses: actions/download-artifact@v3.0.2
        with:
          name: Release Binary

      - name: Download Release data artifacts
        uses: actions/download-artifact@v3.0.2
        with:
          name: Release data artifacts
          path: data

      - name: Zips data files
        run: zip -r data.zip ./data/

      - name: Send Embed
        run: |
          FILE_NAMES=$(ls -1 boiii.exe *.zip 2>/dev/null || true)

          FILE_TABLE=""
          if [ -n "$FILE_NAMES" ]; then
            FILE_TABLE="File Name | \n"
            FILE_TABLE+="--- | --- \n"
            for FILE in $FILE_NAMES; do
              FILE_TABLE+="$FILE | \n"
            done
          else
            FILE_TABLE="No files attached"
          fi
          
          TIMESTAMP=$(TZ=Asia/Karachi date --iso-8601=seconds)
          ESCAPED_TIMESTAMP=$(echo "$TIMESTAMP" | sed 's/"/\\"/g')

          COMMIT_HASH=$(echo "${{ github.sha }}" | cut -c1-7)
          BUILD_NUMBER="[Workflow Run:](https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }})\n\`${{ github.sha }}\`\n[Commit:](https://github.com/${{ github.repository }}/commit/${{ github.sha }})\n\`$COMMIT_HASH\`"
          DESCRIPTION="$BUILD_NUMBER"

          if [ "${{ github.event_name }}" == "workflow_dispatch" ]; then
            TRIGGER_TYPE="Manually Triggered: True\nPull Request: False\nCommit: False"
          elif [ "${{ github.event_name }}" == "pull_request" ]; then
            TRIGGER_TYPE="Manually Triggered: False\nPull Request: True\nCommit: False"
          else
            TRIGGER_TYPE="Manually Triggered: False\nPull Request: False\nCommit: True"
          fi

          JSON_PAYLOAD="{
            \"content\": \"\",
            \"tts\": false,
            \"embeds\": [
              {
                \"description\": \"$DESCRIPTION\",
                \"fields\": [
                  {
                    \"name\": \"Files Attached:\",
                    \"value\": \"\`\`\`$FILE_TABLE\`\`\`\"
                  },
                  {
                    \"id\": 370131057,
                    \"name\": \"Info:\",
                    \"value\": \"\`$TRIGGER_TYPE\`\"
                  }
                ],
                \"title\": \"Build:\",
                \"color\": 16777215,
                \"footer\": {
                  \"text\": \"Biraru Studio's\"
                },
                \"timestamp\": \"$ESCAPED_TIMESTAMP\"
              }
            ],
            \"components\": [],
            \"actions\": {},
            \"username\": \"Builds\"
          }"

          curl -H "Content-Type: application/json" -X POST -d "$JSON_PAYLOAD" ${{ secrets.DISCORD_BUILDS_BOT_WEBHOOK }}

      - name: Upload BOIII binary
        uses: sinshutu/upload-to-discord@v2.0.0
        env:
          DISCORD_WEBHOOK: ${{ secrets.DISCORD_CI_BOT_WEBHOOK }}
        with:
          args: boiii.exe

      - name: Upload data zip
        uses: sinshutu/upload-to-discord@v2.0.0
        env:
          DISCORD_WEBHOOK: ${{ secrets.DISCORD_CI_BOT_WEBHOOK }}
        with:
          args: data.zip

      - name: Prepare cleanup
        run: echo "" > boiii.exe

      - name: Cleanup
        uses: actions/upload-artifact@v3.1.2
        with:
          name: Release Binary
          retention-days: 1
          path: |
            boiii.exe

