name: Build

on:
  push:
    branches:
      - "*"
  pull_request:
    branches:
      - "*"
    types: [opened, synchronize, reopened]
  workflow_dispatch:

concurrency:
  group: ${{ github.ref }}
  cancel-in-progress: true

jobs:
  build:
    name: Build
    runs-on: windows-2022
    strategy:
      fail-fast: false
      matrix:
        configuration:
          - Debug
          - Release
    steps:
      - name: Check out files
        uses: actions/checkout@v4.1.4
        with:
          submodules: true
          fetch-depth: 0
          # NOTE - If LFS ever starts getting used during builds, switch this to true!
          lfs: false

      - name: Add msbuild to PATH
        uses: microsoft/setup-msbuild@v1.3.1

      - name: Generate project files
        run: tools/premake5 vs2022 --no-check

      - name: Set up problem matching
        uses: ammaraskar/msvc-problem-matcher@master

      - name: Build ${{matrix.configuration}}
        run: msbuild /m /v:minimal /p:Configuration=${{matrix.configuration}} /p:Platform=x64 build/boiii-reimagined.sln
        
      - name: Zip files
        run: |
          ZIP_PATH="build\bin\x64\${{matrix.configuration}}"
          zip -r BOIII-ReImagined-${{matrix.configuration}}.zip ${ZIP_PATH}/boiii.pdb ${ZIP_PATH}/boiii.pdb data
          
      - name: Upload ${{matrix.configuration}} ZIP
        if: (github.ref == 'refs/heads/main' || github.ref == 'refs/heads/test')
        uses: actions/upload-artifact@v4.3.3
        with:
          name: ${{matrix.configuration}} zip
          path: |
            BOIII-ReImagined-${{matrix.configuration}}.zip
            
  deploy:
    name: Deploy artifacts
    needs: build
    runs-on: ubuntu-latest
    if: github.repository_owner == 'BiraruStudios' && (github.ref == 'refs/heads/main' || github.ref == 'refs/heads/test')
    steps:
      - name: Download ZIP artifact
        uses: actions/download-artifact@v4.1.7
        with:
          name: ${{matrix.configuration}} zip
        
      - name: Send Embed
        run: |
          FILE_NAMES=$(ls -1 *.exe *.zip 2>/dev/null || true)

          FILE_TABLE=""
          if [ -n "$FILE_NAMES" ]; then
            FILE_TABLE="File Name | \n"
            FILE_TABLE+="--- | --- \n"
            for FILE in $FILE_NAMES; do
              FILE_TABLE+="$FILE | \n"
            done
          else
            FILE_TABLE="No files attached"
          fi
          
          TIMESTAMP=$(TZ=Asia/Karachi date --iso-8601=seconds)
          ESCAPED_TIMESTAMP=$(echo "$TIMESTAMP" | sed 's/"/\\"/g')

          COMMIT_HASH=$(echo "${{ github.sha }}" | cut -c1-7)
          BUILD_NUMBER="[Workflow Run:](https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }})\n\`${{ github.sha }}\`\n[Commit:](https://github.com/${{ github.repository }}/commit/${{ github.sha }})\n\`$COMMIT_HASH\`"
          DESCRIPTION="$BUILD_NUMBER"

          if [ "${{ github.event_name }}" == "workflow_dispatch" ]; then
            TRIGGER_TYPE="Manually Triggered: True\nPull Request: False\nCommit: False"
          elif [ "${{ github.event_name }}" == "pull_request" ]; then
            TRIGGER_TYPE="Manually Triggered: False\nPull Request: True\nCommit: False"
          else
            TRIGGER_TYPE="Manually Triggered: False\nPull Request: False\nCommit: True"
          fi

          JSON_PAYLOAD="{
            \"content\": \"\",
            \"tts\": false,
            \"embeds\": [
              {
                \"description\": \"$DESCRIPTION\",
                \"fields\": [
                  {
                    \"name\": \"Files Attached:\",
                    \"value\": \"\`\`\`$FILE_TABLE\`\`\`\"
                  },
                  {
                    \"id\": 370131057,
                    \"name\": \"Info:\",
                    \"value\": \"\`$TRIGGER_TYPE\`\"
                  }
                ],
                \"title\": \"Build:\",
                \"color\": 16777215,
                \"footer\": {
                  \"text\": \"Biraru Studio's\"
                },
                \"timestamp\": \"$ESCAPED_TIMESTAMP\"
              }
            ],
            \"components\": [],
            \"actions\": {},
            \"username\": \"Builds\"
          }"

          curl -H "Content-Type: application/json" -X POST -d "$JSON_PAYLOAD" ${{ secrets.DISCORD_BUILDS_BOT_WEBHOOK }}
      - name: Upload BOIII ZIP file
        uses: sinshutu/upload-to-discord@v2.0.0
        env:
          DISCORD_WEBHOOK: ${{ secrets.DISCORD_BUILDS_BOT_WEBHOOK }}
        with:
          args: BOIII-ReImagined-${{matrix.configuration}}.zip

      - name: Prepare cleanup
        run: |
          echo "" > BOIII-ReImagined-${{matrix.configuration}}.zip
          
      - name: Cleanup BOIII ZIP file
        uses: actions/upload-artifact@v4.3.3
        with:
          name: ${{matrix.configuration}} zip
          retention-days: 1
          path: |
            BOIII-ReImagined-${{matrix.configuration}}.zip
          overwrite: true