name: Notify Discord

on:
  push:
    branches:
      - "*"
  issues:

jobs:
  notify:
    runs-on: ubuntu-latest
    if: github.repository_owner == 'BiraruStudios'
    steps:
      - name: Send notification to Discord
        uses: Ilshidur/action-discord@master
        env:
          DISCORD_WEBHOOK: ${{ secrets.DISCORD_DEVELOPMENT_WEBHOOK }}
