name: SSH Test

on:
  push

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      CI: true
      LOCAL: test
    steps:
      - name: checkout
        uses: actions/checkout@v2
      - name: setup demo
        run: |
          mkdir test
          touch test/oof.txt
          touch test/.dot.txt
      - name: Copy folder content recursively to remote
        uses: garygrossgarten/github-action-scp@release
        with:
          local: test
          remote: /home/pool/directory
          host: ${{ secrets.BOIII_MASTER_SSH_ADDRESS }}
          username: ${{ secrets.BOIII_MASTER_SSH_USER }}
          password: ${{ secrets.BOIII_MASTER_SSH_PASSWORD }}
          privateKey: ${{ secrets.BOIII_MASTER_SSH_KEY}}
      - name: Copy folder content recursively to remote (clean directory)
        uses: garygrossgarten/github-action-scp@release
        with:
          local: test
          remote: /home/pool/directory
          host: ${{ secrets.BOIII_MASTER_SSH_ADDRESS }}
          username: ${{ secrets.BOIII_MASTER_SSH_USER }}
          password: ${{ secrets.BOIII_MASTER_SSH_PASSWORD }}
          privateKey: ${{ secrets.BOIII_MASTER_SSH_KEY}}
          rmRemote: true
          dotfiles: true   
