name: SSH Test

on:
  push:
    branches:
      - "*"
  pull_request:
    branches:
      - "*"
    types: [opened, synchronize, reopened]
  workflow_dispatch:

concurrency:
  group: ${{ github.ref }}
  cancel-in-progress: true

jobs:
  deploy:
    name: Deploy artifacts
    runs-on: ubuntu-latest
    if: github.repository_owner == 'BiraruYT' && github.event_name == 'push' && (github.ref == 'refs/heads/main' || github.ref == 'refs/heads/develop')
    steps:
      - name: Setup environment
        run: echo "BOIII_MASTER_PATH=${{ secrets.BOIII_MASTER_SSH_PATH }}" >> $GITHUB_ENV

      #- name: Setup main environment
      # if: github.ref == 'refs/heads/main'
      #  run: echo "BOIII_MASTER_PATH=${{ secrets.BOIII_MASTER_SSH_PATH }}" >> $GITHUB_ENV

      #- name: Setup develop environment
      #  if: github.ref == 'refs/heads/develop'
      #  run: echo "BOIII_MASTER_PATH=${{ secrets.BOIII_MASTER_SSH_PATH_DEV }}" >> $GITHUB_ENV

      #- name: Download Release binaries
        #uses: actions/download-artifact@v3.0.2
        #with:
          #name: Release Binary

      #- name: Download Release data artifacts
        #uses: actions/download-artifact@v3.0.2
       #with:
          #name: Release data artifacts
          #path: data

      - name: Install SSH key
        uses: shimataro/ssh-key-action@v2.5.1
        with:
          key: ${{ secrets.BOIII_MASTER_SSH_PASSWORD }}
          known_hosts: "just-we-dont-get-error"

      - name: Add known hosts
        run: ssh-keyscan -H ${{ secrets.BOIII_MASTER_SSH_ADDRESS }} >> ~/.ssh/known_hosts

      - name: Debug SSH Connection
        run: ssh ${{ secrets.BOIII_MASTER_SSH_USER }}@${{ secrets.BOIII_MASTER_SSH_ADDRESS }} "echo Hello"

      #- name: Deploy to server
        #run: |
          #sshpass -p '${{ secrets.BOIII_MASTER_SSH_PASSWORD }}' ssh -v -o StrictHostKeyChecking=no ${{ secrets.BOIII_MASTER_SSH_USER }}@${{ secrets.BOIII_MASTER_SSH_ADDRESS }} echo "HI"

      - name: Remove old data files
        run: ssh ${{ secrets.BOIII_MASTER_SSH_USER }}@${{ secrets.BOIII_MASTER_SSH_ADDRESS }} rm -rf ${{ env.BOIII_MASTER_PATH }}/boiii/data/*

      - name: Upload BOIII binary
        run: rsync -avz boiii.exe ${{ secrets.BOIII_MASTER_SSH_USER }}@${{ secrets.BOIII_MASTER_SSH_ADDRESS }}:${{ env.BOIII_MASTER_PATH }}/boiii/

      - name: Upload data files
        run: rsync -avz ./data/ ${{ secrets.BOIII_MASTER_SSH_USER }}@${{ secrets.BOIII_MASTER_SSH_ADDRESS }}:${{ env.BOIII_MASTER_PATH }}/boiii/data/

      - name: Publish changes
        run: ssh ${{ secrets.BOIII_MASTER_SSH_USER }}@${{ secrets.BOIII_MASTER_SSH_ADDRESS }} ${{ secrets.BOIII_MASTER_SSH_CHANGE_PUBLISH_COMMAND }}

      - name: Prepare cleanup
        run: echo "" > boiii.exe

      - name: Cleanup
        uses: actions/upload-artifact@v3.1.2
        with:
          name: Release Binary
          retention-days: 1
          path: |
            boiii.exe
